config/routes.rb
Bro3at::Application.routes.draw do
  resources :servers

  get "dashboard/index"

  resources :mixis

  resources :bro3s do
    member do
      get 'deck'
    end
  end

  root :to => 'dashboard#index'

end

app/models/mixi.rb
#-*- coding: utf-8 -*-
#
require 'browser'

class Mixi < ActiveRecord::Base
  attr_accessible :email, :name, :password

  attr_reader :ua

  validates :name,  :presence => true
  validates :email, :presence => true, :email => true

  class LoginError < Exception; end

  def login
    retry_count = 3
    @ua = Browser.new
    @ua.cookie_jar.load cookies_path if File.exists? cookies_path
    begin

      test_login
    rescue LoginError => e
      retry_count -= 1
      if retry_count > 0
        do_login
        retry
      end
    ensure
      FileUtils.mkdir_p File.dirname(cookies_path)
      @ua.cookie_jar.save_as cookies_path
    end

     if @ua.page.title =~ /ブラウザ三国志/
       return true
     else
       return false
     end
  end

  def test_login
    doc = @ua.get 'http://mixi.jp/run_appli.pl?id=6598'
    if doc.uri.path == '/redirect_next_url.pl'
      raise LoginError, "Login failed"
    else
      return true
    end
  end

  def do_login
    @ua.page.form_with :name => 'login_form'  do |form|
      form.field_with(:name => 'email').value = email
      form.field_with(:name => 'password').value = password
      form.checkbox_with(:name => 'sticky').check
      form.submit
    end
    puts @ua.page.content
  end

  def cookies_path
    File.join ::Rails.root.to_s, 'tmp', 'cookies', 'account.%d.txt' % id
  end
end

app/controllers/mixis_controller.rb
class MixisController < ApplicationController
  # GET /mixis
  # GET /mixis.json
  def index
    @mixis = Mixi.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @mixis }
    end
  end

  # GET /mixis/1
  # GET /mixis/1.json
  def show
    @mixi = Mixi.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @mixi }
    end
  end

  # GET /mixis/new
  # GET /mixis/new.json
  def new
    @mixi = Mixi.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @mixi }
    end
  end

  # GET /mixis/1/edit
  def edit
    @mixi = Mixi.find(params[:id])
  end

  # POST /mixis
  # POST /mixis.json
  def create
    @mixi = Mixi.new(params[:mixi])

    respond_to do |format|
      if @mixi.save
        format.html { redirect_to @mixi, notice: 'Mixi was successfully created.' }
        format.json { render json: @mixi, status: :created, location: @mixi }
      else
        format.html { render action: "new" }
        format.json { render json: @mixi.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /mixis/1
  # PUT /mixis/1.json
  def update
    @mixi = Mixi.find(params[:id])

    respond_to do |format|
      if @mixi.update_attributes(params[:mixi])
        format.html { redirect_to @mixi, notice: 'Mixi was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @mixi.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mixis/1
  # DELETE /mixis/1.json
  def destroy
    @mixi = Mixi.find(params[:id])
    @mixi.destroy

    respond_to do |format|
      format.html { redirect_to mixis_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/mixis_helper.rb
module MixisHelper
end

app/views/mixis/_form.html.haml
= form_for @mixi do |f|
  - if @mixi.errors.any?
    #error_explanation
      %h2= "#{pluralize(@mixi.errors.count, "error")} prohibited this mixi from being saved:"
      %ul
        - @mixi.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :email
    = f.email_field :email
  .field
    = f.label :password
    = f.password_field :password
  .actions
    = f.submit 'Save'

app/views/mixis/edit.html.haml
%h1 Editing mixi

= render 'form'

= link_to 'Show', @mixi
\|
= link_to 'Back', mixis_path

app/views/mixis/index.html.haml
%h2 Mixiアカウント

%table.table
  %tr
    %th ID
    %th Name
    %th Email
    %th

  - @mixis.each do |mixi|
    %tr
      %td= mixi.id
      %td= mixi.name
      %td= mixi.email
      %td
        = link_to 'Show', mixi, class: 'btn'
        = link_to 'Edit', edit_mixi_path(mixi), class: 'btn'
        = link_to 'Destroy', mixi, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn'

%br

= link_to 'New Mixi', new_mixi_path

app/views/mixis/new.html.haml
%h1 New mixi

= render 'form'

= link_to 'Back', mixis_path

app/views/mixis/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @mixi.name
%p
  %b Email:
  = @mixi.email
%p
  %b Password:
  = @mixi.password.replace('********')

= link_to 'Edit', edit_mixi_path(@mixi)
\|
= link_to 'Back', mixis_path