config/routes.rb
Bro3at::Application.routes.draw do
  resources :servers

  get "dashboard/index"

  resources :mixis

  resources :bro3s do
    member do
      get 'deck'
    end
  end

  root :to => 'dashboard#index'

end

app/models/server.rb
class Server < ActiveRecord::Base
  attr_accessible :name
end

app/controllers/servers_controller.rb
class ServersController < ApplicationController
  # GET /servers
  # GET /servers.json
  def index
    @servers = Server.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @servers }
    end
  end

  # GET /servers/1
  # GET /servers/1.json
  def show
    @server = Server.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @server }
    end
  end

  # GET /servers/new
  # GET /servers/new.json
  def new
    @server = Server.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @server }
    end
  end

  # GET /servers/1/edit
  def edit
    @server = Server.find(params[:id])
  end

  # POST /servers
  # POST /servers.json
  def create
    @server = Server.new(params[:server])

    respond_to do |format|
      if @server.save
        format.html { redirect_to @server, notice: 'Server was successfully created.' }
        format.json { render json: @server, status: :created, location: @server }
      else
        format.html { render action: "new" }
        format.json { render json: @server.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /servers/1
  # PUT /servers/1.json
  def update
    @server = Server.find(params[:id])

    respond_to do |format|
      if @server.update_attributes(params[:server])
        format.html { redirect_to @server, notice: 'Server was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @server.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /servers/1
  # DELETE /servers/1.json
  def destroy
    @server = Server.find(params[:id])
    @server.destroy

    respond_to do |format|
      format.html { redirect_to servers_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/servers_helper.rb
module ServersHelper
end

app/views/servers/_form.html.haml
= form_for @server do |f|
  - if @server.errors.any?
    #error_explanation
      %h2= "#{pluralize(@server.errors.count, "error")} prohibited this server from being saved:"
      %ul
        - @server.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .actions
    = f.submit 'Save'

app/views/servers/edit.html.haml
%h1 Editing server

= render 'form'

= link_to 'Show', @server
\|
= link_to 'Back', servers_path

app/views/servers/index.html.haml
%h1 サーバー

%table.table
  %tr
    %th Name
    %th

  - @servers.each do |server|
    %tr
      %td= server.name
      %td
        = link_to 'Show', server 
        = link_to 'Edit', edit_server_path(server)
        = button_to 'Destroy', server, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Server', new_server_path

app/views/servers/new.html.haml
%h1 New server

= render 'form'

= link_to 'Back', servers_path

app/views/servers/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @server.name

= link_to 'Edit', edit_server_path(@server)
\|
= link_to 'Back', servers_path